package agenciaviajes.presentacion;

import agenciaviajes.negocio.Cliente;
import agenciaviajes.negocio.GestorClientes;
import agenciaviajes.negocio.Plan;
import agenciaviajes.utils.Utilidades;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import mvcf.AModel;
import mvcf.AView;

public class GUIClientesPotenciales extends javax.swing.JFrame implements AView{

    private GestorClientes miGestor = new GestorClientes();
    
    public GUIClientesPotenciales() {
        initComponents();
        cambiarLista();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanelNorte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        myBoton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        myPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        myPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clientes Potenciales Por Plan Turistico");

        myPanelNorte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        myPanelNorte.setForeground(new java.awt.Color(0, 51, 204));
        myPanelNorte.setPreferredSize(new java.awt.Dimension(400, 80));

        jLabel1.setText("Selecciones el Plan:");
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 20));
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myPanelNorte.add(jLabel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(100, 50));
        myPanelNorte.add(jComboBox1);

        myBoton.setText("Buscar Clientes Potenciales");
        myBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myBotonActionPerformed(evt);
            }
        });
        myPanelNorte.add(myBoton);

        getContentPane().add(myPanelNorte, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new java.awt.BorderLayout());

        myPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        myPanel1.setPreferredSize(new java.awt.Dimension(507, 50));

        jLabel3.setText("Resultados: ");
        myPanel1.add(jLabel3);

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        myPanel1.add(jTextField1);

        jPanel2.add(myPanel1, java.awt.BorderLayout.PAGE_START);

        myPanel2.setLayout(new java.awt.BorderLayout());

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        myPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(myPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myBotonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIClientesPotenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIClientesPotenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIClientesPotenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIClientesPotenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIClientesPotenciales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton myBoton;
    private javax.swing.JPanel myPanel1;
    private javax.swing.JPanel myPanel2;
    private javax.swing.JPanel myPanelNorte;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables

    public void cambiarLista()
    {
        ArrayList<Plan> misPlanes = miGestor.obtenerPlanesServidor();
        String[] listaPlanes = new String[misPlanes.size()];
        for(int i=0; i < misPlanes.size(); i++)
        {
            String item = misPlanes.get(i).getNombrePlan();
            listaPlanes[i] = item;
        }
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(listaPlanes));
                    
    }

    private void inicializarTabla() {

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Id", "Nombres", "Apellidos", "Fecha Nacimiento", "Sexo", "Email"
                }
        ));
    }
    
    private void llenarTabla(ArrayList<Cliente> clientes) {
        this.inicializarTabla();
        DefaultTableModel model = (DefaultTableModel) tblClientes.getModel();

        Object rowData[] = new Object[7];
        for (Cliente cli : clientes) {
            rowData[0] = cli.getId();
            rowData[1] = cli.getNombres();
            rowData[2] = cli.getApellidos();
            rowData[3] = cli.getFechaNacimiento();
            rowData[4] = cli.getSexo();
            rowData[5] = cli.getEmail();
            model.addRow(rowData);
        }
    }
    @Override
    public void actualizar(AModel amodel) 
    {  
            GestorClientes gestor = (GestorClientes) amodel;
            ArrayList<Cliente> listado = gestor.obtenerClientes();
            llenarTabla(listado);
      
    
            
    }
    
    public JButton obtenerButon()
    {
        return myBoton;
    }
}
