/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenciaviajes.presentacion;

import agenciaviajes.negocio.Cliente;
import agenciaviajes.negocio.GestorClientes;
import agenciaviajes.utils.Utilidades;
import java.awt.Color;
import java.awt.Graphics;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import mvcf.AModel;
import mvcf.AView;

/**
 *
 * @author LENOVO
 */
public class GUIGraficaClientes extends javax.swing.JFrame implements AView{

    private int cantidaHombres;
    private int cantidadMujeres;
    //Variables para la grafica de porcentajes
    private float porcentajeHombres;
    private float  porcentajeMujeres;
    private static final int ancho = 100;
    private static final int alto = 260;
    private int altoHombres;
    private int altoMujeres;
    /**
     * Constructor
     * 
     * @param h posicion horizontal
     * @param v posicion vertical
     */
    public GUIGraficaClientes(int h, int v) {
        cantidaHombres = 0;
        cantidadMujeres=0;
        initComponents();
        initComponents();
        setSize(500, 500);
        setLocation(h, v);
        setVisible(true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grafica de los Clientes");

        myPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(myPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel myPanel;
    // End of variables declaration//GEN-END:variables

 
    
    @Override
    public void actualizar(AModel amodel) {
        try {
            GestorClientes gestor = (GestorClientes) amodel;
            ArrayList<Cliente> listado = gestor.consultarClientes();
            cantidaHombres = gestor.getTotalHombresV2();
            cantidadMujeres = gestor.getTotalMujeresV2();
            graficar(cantidaHombres, cantidadMujeres);
          
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(GUIClientesVer.class.getName()).log(Level.SEVERE, null, ex);
            Utilidades.mensajeError("Error al consultar clientes", "Atención");
        }
    }
    
    private void graficar(int totalHombres, int totalMujeres)
    {
        //Total de personas, hombre y mujeres.
        int totalPersonas = totalHombres + totalMujeres;
        
        //Obtenemos los porcentajes con rexpecto a los hombres y las mujeres
        this.porcentajeHombres = (100 * ((float)(totalHombres))) / ((float)(totalPersonas));
        this.porcentajeMujeres = (100 * ((float)(totalMujeres))) / ((float)(totalPersonas));
        
        //En estas variables calculamos el porcentaje que hay que pintar en los rectangulos
        this.altoHombres = (((int)(porcentajeHombres)) * alto) / 100; 
        this.altoMujeres = (((int)(porcentajeMujeres)) * alto) / 100; 
        
        Graphics g = myPanel.getGraphics();
        //Implementamos un metodo que dibuje las graficas de porcentajes
        paintComponent(g);
     
    }
    
    //Metodo de dibujo
    @SuppressWarnings("empty-statement")
    public void paintComponent(Graphics g )
    {
        super.paintComponents(g);;
        
        g.setColor(Color.black);
        g.drawRect(60, 60, ancho, alto);
        g.drawRect(260, 60, ancho, alto);
        
        g.drawString("Hombres", 65, 345);
        g.drawString("Mujeres", 265, 345);
        g.drawString("" + porcentajeHombres +" %", 90, 55);
        g.drawString("" + porcentajeMujeres + " %", 290, 55);
       
        g.setColor(Color.RED);
        g.fillRect(61, 60 + (alto - altoHombres), ancho-1, altoHombres);
        g.fillRect(261, 60 + (alto- altoMujeres), ancho-1, altoMujeres);
    }
}



